# Generated by Django 5.0.7 on 2024-07-18 01:26

import django.db.models.deletion
import grab.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0002_profile_alter_post_publisher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_topic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/userprofile.png', upload_to=grab.models.getFileName),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='topic',
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
