# Generated by Django 5.0.7 on 2024-07-18 01:49

import grab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0003_remove_post_publish_topic_remove_post_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='userprofile.png', upload_to=grab.models.getFileName),
        ),
    ]
