# Generated by Django 5.0.7 on 2024-07-18 14:32

import grab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/images/logo.png', upload_to=grab.models.getFileName),
        ),
    ]
