# Generated by Django 5.0.7 on 2024-07-18 14:40

import grab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grab', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='image/userprofile.png', upload_to=grab.models.getFileName),
        ),
    ]
